# Generated by Django 5.1.3 on 2024-11-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_ordergroup_order_order_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
