# Generated by Django 5.1.3 on 2024-12-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
