# Generated by Django 5.1.3 on 2024-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_product_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredient',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
