# Generated by Django 5.1.3 on 2024-12-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_address_is_default_profile_default_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_address',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='address_line',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10),
        ),
    ]
