# Generated by Django 5.1.3 on 2024-12-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_ordergroup_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroup',
            name='delivery_method',
            field=models.CharField(choices=[('تحویل حضوری', 'تحویل حضوری'), ('ارسال با پیک', 'ارسال با پیک')], default='دریافت حضوری', max_length=50),
        ),
    ]
